import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/components/Provider'
import ProtectedRoute from '@/lib/ProtectRoute'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          <ProtectedRoute>
            <Navbar />
            {children}
          </ProtectedRoute>
        </Providers>
      </body>
    </html>
  )
}
